# EXERCICE 1

In [36]:
import pandas as pd

In [37]:
data = pd.read_csv("tweets.csv")

In [38]:
data

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,LOSER! https://t.co/p5imhMJqS1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,Most of the money raised by the RINO losers of...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,....because they don’t know how to win and the...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,....lost for Evan “McMuffin” McMullin (to me)....,05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,....get even for all of their many failures. Y...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,.@Cher attacked @MittRomney. She is an average...,05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,Firing @lisalampanelli may have come as a surp...,05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,My @SquawkCNBC interview discussing why @MittR...,03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,I feel sorry for Rosie 's new partner in love ...,12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,The S&P are losers. They did this for personal...,08-09-2011 17:40:33,209,19,False,100984825103663104

In [39]:
# Supprimer les poncuations
import string
ponc = string.punctuation
for i in range(len(data)):
    data["text"][i] = "".join([w for w in data["text"][i] if w not in ponc])
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/1822127644.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = "".join([w for w in data["text"][i] if w not in ponc])

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,LOSER httpstcop5imhMJqS1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,Most of the money raised by the RINO losers of...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,because they don’t know how to win and their s...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,lost for Evan “McMuffin” McMullin to me Steve ...,05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,get even for all of their many failures You se...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,Cher attacked MittRomney She is an average tal...,05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,Firing lisalampanelli may have come as a surpr...,05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,My SquawkCNBC interview discussing why MittRom...,03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,I feel sorry for Rosie s new partner in love w...,12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,The SP are losers They did this for personal p...,08-09-2011 17:40:33,209,19,False,100984825103663104

In [40]:
# tokinisation en minuscul
import nltk
for i in range(len(data)):
    data["text"][i] = data["text"][i].lower()
    data["text"][i] = nltk.word_tokenize(data["text"][i])
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/2141576101.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = data["text"][i].lower()
C:\Users\adnane\AppData\Local\Temp/ipykernel_580/2141576101.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = nltk.word_tokenize(data["text"][i])

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,"[loser, httpstcop5imhmjqs1]",05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,"[most, of, the, money, raised, by, the, rino, ...",05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,"[because, they, don, ’, t, know, how, to, win,...",05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,"[lost, for, evan, “, mcmuffin, ”, mcmullin, to...",05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,"[get, even, for, all, of, their, many, failure...",05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,"[cher, attacked, mittromney, she, is, an, aver...",05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,"[firing, lisalampanelli, may, have, come, as, ...",05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,"[my, squawkcnbc, interview, discussing, why, m...",03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,"[i, feel, sorry, for, rosie, s, new, partner, ...",12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,"[the, sp, are, losers, they, did, this, for, p...",08-09-2011 17:40:33,209,19,False,100984825103663104

In [41]:
# Suppresion des stopwords
from nltk.corpus import stopwords
stopwords_en = set(stopwords.words('english'))
for i in range(len(data)):
    data["text"][i] = [w for w in data["text"][i] if w not in stopwords_en]
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/19334190.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = [w for w in data["text"][i] if w not in stopwords_en]

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,"[loser, httpstcop5imhmjqs1]",05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,"[money, raised, rino, losers, socalled, “, lin...",05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,"[’, know, win, socalled, lincoln, project, dis...",05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,"[lost, evan, “, mcmuffin, ”, mcmullin, steve, ...",05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,"[get, even, many, failures, see, loser, types,...",05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,"[cher, attacked, mittromney, average, talent, ...",05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,"[firing, lisalampanelli, may, come, surprise, ...",05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,"[squawkcnbc, interview, discussing, mittromney...",03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,"[feel, sorry, rosie, new, partner, love, whose...",12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,"[sp, losers, personal, publicity, order, strai...",08-09-2011 17:40:33,209,19,False,100984825103663104

In [42]:
# Supprimer les mors inf à 3
for i in range(len(data)):
    data["text"][i] = [w for w in data["text"][i] if len(w)>3]
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/1746295422.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = [w for w in data["text"][i] if len(w)>3]

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,"[loser, httpstcop5imhmjqs1]",05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,"[money, raised, rino, losers, socalled, lincol...",05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,"[know, socalled, lincoln, project, disgrace, h...",05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,"[lost, evan, mcmuffin, mcmullin, steve, schmid...",05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,"[even, many, failures, loser, types, care, fed...",05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,"[cher, attacked, mittromney, average, talent, ...",05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,"[firing, lisalampanelli, come, surprise, stron...",05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,"[squawkcnbc, interview, discussing, mittromney...",03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,"[feel, sorry, rosie, partner, love, whose, par...",12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,"[losers, personal, publicity, order, straighte...",08-09-2011 17:40:33,209,19,False,100984825103663104

In [43]:
# Stemming
from nltk.stem import PorterStemmer
stem = PorterStemmer()
for i in range(len(data)):
    data["text"][i] = [stem.stem(w) for w in data["text"][i]]
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/1620234929.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = [stem.stem(w) for w in data["text"][i]]

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,"[loser, httpstcop5imhmjqs1]",05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,"[money, rais, rino, loser, socal, lincoln, pro...",05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,"[know, socal, lincoln, project, disgrac, hones...",05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,"[lost, evan, mcmuffin, mcmullin, steve, schmid...",05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,"[even, mani, failur, loser, type, care, feder,...",05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,"[cher, attack, mittromney, averag, talent, tou...",05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,"[fire, lisalampanelli, come, surpris, strong, ...",05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,"[squawkcnbc, interview, discuss, mittromney, g...",03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,"[feel, sorri, rosi, partner, love, whose, pare...",12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,"[loser, person, public, order, straighten, ter...",08-09-2011 17:40:33,209,19,False,100984825103663104

In [44]:
# Clean_text
for i in range(len(data)):
    data["text"][i] = " ".join(data["text"][i])
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/2865262161.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"][i] = " ".join(data["text"][i])

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,loser httpstcop5imhmjqs1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,money rais rino loser socal lincoln project go...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,know socal lincoln project disgrac honest know...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,lost evan mcmuffin mcmullin steve schmidt reed...,05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,even mani failur loser type care feder judg gr...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274
...,...,...,...,...,...,...,...
256,Twitter Web Client,cher attack mittromney averag talent touch rea...,05-10-2012 15:10:23,715,465,False,200603697435246592
257,Twitter Web Client,fire lisalampanelli come surpris strong player...,05-07-2012 02:58:18,45,19,False,199332301463748609
258,Twitter Web Client,squawkcnbc interview discuss mittromney great ...,03-06-2012 17:07:51,32,9,False,177078050750599168
259,TweetDeck,feel sorri rosi partner love whose parent deva...,12-14-2011 16:45:55,667,463,False,146994336670822400
260,TweetDeck,loser person public order straighten terribl r...,08-09-2011 17:40:33,209,19,False,100984825103663104

In [45]:
# 2-gramme
import re
from nltk.util import ngrams
data["2-gramme"] = ""
for i in range(len(data)):
    data["2-gramme"][i] = [t for t in data["text"][i].split(" ")]
    data["2-gramme"][i] = list(ngrams(data["2-gramme"][i], 2))
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/483053051.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2-gramme"][i] = [t for t in data["text"][i].split(" ")]
C:\Users\adnane\AppData\Local\Temp/ipykernel_580/483053051.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2-gramme"][i] = list(ngrams(data["2-gramme"][i], 2))

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,2-gramme
0,Twitter for iPhone,loser httpstcop5imhmjqs1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416,"[(loser, httpstcop5imhmjqs1)]"
1,Twitter for iPhone,money rais rino loser socal lincoln project go...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874,"[(money, rais), (rais, rino), (rino, loser), (..."
2,Twitter for iPhone,know socal lincoln project disgrac honest know...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782,"[(know, socal), (socal, lincoln), (lincoln, pr..."
3,Twitter for iPhone,lost evan mcmuffin mcmullin steve schmidt reed...,05-05-2020 04:46:34,13855,62268,False,1257532114666508291,"[(lost, evan), (evan, mcmuffin), (mcmuffin, mc..."
4,Twitter for iPhone,even mani failur loser type care feder judg gr...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274,"[(even, mani), (mani, failur), (failur, loser)..."
...,...,...,...,...,...,...,...,...
256,Twitter Web Client,cher attack mittromney averag talent touch rea...,05-10-2012 15:10:23,715,465,False,200603697435246592,"[(cher, attack), (attack, mittromney), (mittro..."
257,Twitter Web Client,fire lisalampanelli come surpris strong player...,05-07-2012 02:58:18,45,19,False,199332301463748609,"[(fire, lisalampanelli), (lisalampanelli, come..."
258,Twitter Web Client,squawkcnbc interview discuss mittromney great ...,03-06-2012 17:07:51,32,9,False,177078050750599168,"[(squawkcnbc, interview), (interview, discuss)..."
259,TweetDeck,feel sorri rosi partner love whose parent deva...,12-14-2011 16:45:55,667,463,False,146994336670822400,"[(feel, sorri), (sorri, rosi), (rosi, partner)..."
260,TweetDeck,loser person public order straighten terribl r...,08-09-2011 17:40:33,209,19,False,100984825103663104,"[(loser, person), (person, public), (public, o..."

In [47]:
data["3-gramme"] = ""
for i in range(len(data)):
    data["3-gramme"][i] = [t for t in data["text"][i].split(" ")]
    data["3-gramme"][i] = list(ngrams(data["3-gramme"][i], 3))
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/910999389.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["3-gramme"][i] = [t for t in data["text"][i].split(" ")]
C:\Users\adnane\AppData\Local\Temp/ipykernel_580/910999389.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["3-gramme"][i] = list(ngrams(data["3-gramme"][i], 3))

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,2-gramme,3-gramme
0,Twitter for iPhone,loser httpstcop5imhmjqs1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416,"[(loser, httpstcop5imhmjqs1)]",[]
1,Twitter for iPhone,money rais rino loser socal lincoln project go...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874,"[(money, rais), (rais, rino), (rino, loser), (...","[(money, rais, rino), (rais, rino, loser), (ri..."
2,Twitter for iPhone,know socal lincoln project disgrac honest know...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782,"[(know, socal), (socal, lincoln), (lincoln, pr...","[(know, socal, lincoln), (socal, lincoln, proj..."
3,Twitter for iPhone,lost evan mcmuffin mcmullin steve schmidt reed...,05-05-2020 04:46:34,13855,62268,False,1257532114666508291,"[(lost, evan), (evan, mcmuffin), (mcmuffin, mc...","[(lost, evan, mcmuffin), (evan, mcmuffin, mcmu..."
4,Twitter for iPhone,even mani failur loser type care feder judg gr...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274,"[(even, mani), (mani, failur), (failur, loser)...","[(even, mani, failur), (mani, failur, loser), ..."
...,...,...,...,...,...,...,...,...,...
256,Twitter Web Client,cher attack mittromney averag talent touch rea...,05-10-2012 15:10:23,715,465,False,200603697435246592,"[(cher, attack), (attack, mittromney), (mittro...","[(cher, attack, mittromney), (attack, mittromn..."
257,Twitter Web Client,fire lisalampanelli come surpris strong player...,05-07-2012 02:58:18,45,19,False,199332301463748609,"[(fire, lisalampanelli), (lisalampanelli, come...","[(fire, lisalampanelli, come), (lisalampanelli..."
258,Twitter Web Client,squawkcnbc interview discuss mittromney great ...,03-06-2012 17:07:51,32,9,False,177078050750599168,"[(squawkcnbc, interview), (interview, discuss)...","[(squawkcnbc, interview, discuss), (interview,..."
259,TweetDeck,feel sorri rosi partner love whose parent deva...,12-14-2011 16:45:55,667,463,False,146994336670822400,"[(feel, sorri), (sorri, rosi), (rosi, partner)...","[(feel, sorri, rosi), (sorri, rosi, partner), ..."
260,TweetDeck,loser person public order straighten terribl r...,08-09-2011 17:40:33,209,19,False,100984825103663104,"[(loser, person), (person, public), (public, o...","[(loser, person, public), (person, public, ord..."

In [48]:
data["4-gramme"] = ""
for i in range(len(data)):
    data["4-gramme"][i] = [t for t in data["text"][i].split(" ")]
    data["4-gramme"][i] = list(ngrams(data["4-gramme"][i], 4))
data

C:\Users\adnane\AppData\Local\Temp/ipykernel_580/474611176.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["4-gramme"][i] = [t for t in data["text"][i].split(" ")]
C:\Users\adnane\AppData\Local\Temp/ipykernel_580/474611176.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["4-gramme"][i] = list(ngrams(data["4-gramme"][i], 4))

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,2-gramme,3-gramme,4-gramme
0,Twitter for iPhone,loser httpstcop5imhmjqs1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416,"[(loser, httpstcop5imhmjqs1)]",[],[]
1,Twitter for iPhone,money rais rino loser socal lincoln project go...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874,"[(money, rais), (rais, rino), (rino, loser), (...","[(money, rais, rino), (rais, rino, loser), (ri...","[(money, rais, rino, loser), (rais, rino, lose..."
2,Twitter for iPhone,know socal lincoln project disgrac honest know...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782,"[(know, socal), (socal, lincoln), (lincoln, pr...","[(know, socal, lincoln), (socal, lincoln, proj...","[(know, socal, lincoln, project), (socal, linc..."
3,Twitter for iPhone,lost evan mcmuffin mcmullin steve schmidt reed...,05-05-2020 04:46:34,13855,62268,False,1257532114666508291,"[(lost, evan), (evan, mcmuffin), (mcmuffin, mc...","[(lost, evan, mcmuffin), (evan, mcmuffin, mcmu...","[(lost, evan, mcmuffin, mcmullin), (evan, mcmu..."
4,Twitter for iPhone,even mani failur loser type care feder judg gr...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274,"[(even, mani), (mani, failur), (failur, loser)...","[(even, mani, failur), (mani, failur, loser), ...","[(even, mani, failur, loser), (mani, failur, l..."
...,...,...,...,...,...,...,...,...,...,...
256,Twitter Web Client,cher attack mittromney averag talent touch rea...,05-10-2012 15:10:23,715,465,False,200603697435246592,"[(cher, attack), (attack, mittromney), (mittro...","[(cher, attack, mittromney), (attack, mittromn...","[(cher, attack, mittromney, averag), (attack, ..."
257,Twitter Web Client,fire lisalampanelli come surpris strong player...,05-07-2012 02:58:18,45,19,False,199332301463748609,"[(fire, lisalampanelli), (lisalampanelli, come...","[(fire, lisalampanelli, come), (lisalampanelli...","[(fire, lisalampanelli, come, surpris), (lisal..."
258,Twitter Web Client,squawkcnbc interview discuss mittromney great ...,03-06-2012 17:07:51,32,9,False,177078050750599168,"[(squawkcnbc, interview), (interview, discuss)...","[(squawkcnbc, interview, discuss), (interview,...","[(squawkcnbc, interview, discuss, mittromney),..."
259,TweetDeck,feel sorri rosi partner love whose parent deva...,12-14-2011 16:45:55,667,463,False,146994336670822400,"[(feel, sorri), (sorri, rosi), (rosi, partner)...","[(feel, sorri, rosi), (sorri, rosi, partner), ...","[(feel, sorri, rosi, partner), (sorri, rosi, p..."
260,TweetDeck,loser person public order straighten terribl r...,08-09-2011 17:40:33,209,19,False,100984825103663104,"[(loser, person), (person, public), (public, o...","[(loser, person, public), (person, public, ord...","[(loser, person, public, order), (person, publ..."

# EXERCICE 2

In [128]:
data2 = open("Natural_Language_Processing_Text.txt")

In [129]:
data2 = data2.read()

In [130]:
# convertir text en minuscul 
data2 = data2.lower()
data2

"once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. so when they were old enough, she sent them out into the world to seek their fortunes.\n\nthe first little pig was very lazy. he didn't want to work at all and he built his house out of straw. the second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. then, they sang and danced and played together the rest of the day.\n\nthe third little pig worked hard all day and built his house with bricks. it was a sturdy house complete with a fine fireplace and chimney. it looked like it could withstand the strongest winds."

In [131]:
# Suppression des stop words
from nltk.corpus import stopwords
stopwords_en = set(stopwords.words('english'))
data2 = data2.split(" ")
data2 = [w for w in data2 if w not in stopwords_en]
data2 = " ".join(data2)
data2

'upon time old mother pig three little pigs enough food feed them. old enough, sent world seek fortunes.\n\nthe first little pig lazy. want work built house straw. second little pig worked little bit harder somewhat lazy built house sticks. then, sang danced played together rest day.\n\nthe third little pig worked hard day built house bricks. sturdy house complete fine fireplace chimney. looked like could withstand strongest winds.'

In [132]:
# tokenisation
data2 = data2.split(".")
for i in range(len(data2)):
    data2[i] = data2[i].strip()
data2

['upon time old mother pig three little pigs enough food feed them',
 'old enough, sent world seek fortunes',
 'the first little pig lazy',
 'want work built house straw',
 'second little pig worked little bit harder somewhat lazy built house sticks',
 'then, sang danced played together rest day',
 'the third little pig worked hard day built house bricks',
 'sturdy house complete fine fireplace chimney',
 'looked like could withstand strongest winds',
 '']

In [133]:
def n_gramme(data, n):
    data_n_gramme = [w for w in data.split(" ")]
    data_n_gramme = list(ngrams(data_n_gramme,n))
    return data_n_gramme

In [134]:
data2_2_gramme = []
for i in range(len(data2)):
    data2_2_gramme.append(n_gramme(data2[i],2))
data2_2_gramme

[[('upon', 'time'),
  ('time', 'old'),
  ('old', 'mother'),
  ('mother', 'pig'),
  ('pig', 'three'),
  ('three', 'little'),
  ('little', 'pigs'),
  ('pigs', 'enough'),
  ('enough', 'food'),
  ('food', 'feed'),
  ('feed', 'them')],
 [('old', 'enough,'),
  ('enough,', 'sent'),
  ('sent', 'world'),
  ('world', 'seek'),
  ('seek', 'fortunes')],
 [('the', 'first'), ('first', 'little'), ('little', 'pig'), ('pig', 'lazy')],
 [('want', 'work'), ('work', 'built'), ('built', 'house'), ('house', 'straw')],
 [('second', 'little'),
  ('little', 'pig'),
  ('pig', 'worked'),
  ('worked', 'little'),
  ('little', 'bit'),
  ('bit', 'harder'),
  ('harder', 'somewhat'),
  ('somewhat', 'lazy'),
  ('lazy', 'built'),
  ('built', 'house'),
  ('house', 'sticks')],
 [('then,', 'sang'),
  ('sang', 'danced'),
  ('danced', 'played'),
  ('played', 'together'),
  ('together', 'rest'),
  ('rest', 'day')],
 [('the', 'third'),
  ('third', 'little'),
  ('little', 'pig'),
  ('pig', 'worked'),
  ('worked', 'hard'),
  ('hard', 'day'),
  ('day', 'built'),
  ('built', 'house'),
  ('house', 'bricks')],
 [('sturdy', 'house'),
  ('house', 'complete'),
  ('complete', 'fine'),
  ('fine', 'fireplace'),
  ('fireplace', 'chimney')],
 [('looked', 'like'),
  ('like', 'could'),
  ('could', 'withstand'),
  ('withstand', 'strongest'),
  ('strongest', 'winds')],
 []]

In [136]:
data2_3_gramme = []
for i in range(len(data2)):
    data2_3_gramme.append(n_gramme(data2[i],3))
data2_3_gramme

[[('upon', 'time', 'old'),
  ('time', 'old', 'mother'),
  ('old', 'mother', 'pig'),
  ('mother', 'pig', 'three'),
  ('pig', 'three', 'little'),
  ('three', 'little', 'pigs'),
  ('little', 'pigs', 'enough'),
  ('pigs', 'enough', 'food'),
  ('enough', 'food', 'feed'),
  ('food', 'feed', 'them')],
 [('old', 'enough,', 'sent'),
  ('enough,', 'sent', 'world'),
  ('sent', 'world', 'seek'),
  ('world', 'seek', 'fortunes')],
 [('the', 'first', 'little'),
  ('first', 'little', 'pig'),
  ('little', 'pig', 'lazy')],
 [('want', 'work', 'built'),
  ('work', 'built', 'house'),
  ('built', 'house', 'straw')],
 [('second', 'little', 'pig'),
  ('little', 'pig', 'worked'),
  ('pig', 'worked', 'little'),
  ('worked', 'little', 'bit'),
  ('little', 'bit', 'harder'),
  ('bit', 'harder', 'somewhat'),
  ('harder', 'somewhat', 'lazy'),
  ('somewhat', 'lazy', 'built'),
  ('lazy', 'built', 'house'),
  ('built', 'house', 'sticks')],
 [('then,', 'sang', 'danced'),
  ('sang', 'danced', 'played'),
  ('danced', 'played', 'together'),
  ('played', 'together', 'rest'),
  ('together', 'rest', 'day')],
 [('the', 'third', 'little'),
  ('third', 'little', 'pig'),
  ('little', 'pig', 'worked'),
  ('pig', 'worked', 'hard'),
  ('worked', 'hard', 'day'),
  ('hard', 'day', 'built'),
  ('day', 'built', 'house'),
  ('built', 'house', 'bricks')],
 [('sturdy', 'house', 'complete'),
  ('house', 'complete', 'fine'),
  ('complete', 'fine', 'fireplace'),
  ('fine', 'fireplace', 'chimney')],
 [('looked', 'like', 'could'),
  ('like', 'could', 'withstand'),
  ('could', 'withstand', 'strongest'),
  ('withstand', 'strongest', 'winds')],
 []]

In [137]:
data2_4_gramme = []
for i in range(len(data2)):
    data2_4_gramme.append(n_gramme(data2[i],4))
data2_4_gramme

[[('upon', 'time', 'old', 'mother'),
  ('time', 'old', 'mother', 'pig'),
  ('old', 'mother', 'pig', 'three'),
  ('mother', 'pig', 'three', 'little'),
  ('pig', 'three', 'little', 'pigs'),
  ('three', 'little', 'pigs', 'enough'),
  ('little', 'pigs', 'enough', 'food'),
  ('pigs', 'enough', 'food', 'feed'),
  ('enough', 'food', 'feed', 'them')],
 [('old', 'enough,', 'sent', 'world'),
  ('enough,', 'sent', 'world', 'seek'),
  ('sent', 'world', 'seek', 'fortunes')],
 [('the', 'first', 'little', 'pig'), ('first', 'little', 'pig', 'lazy')],
 [('want', 'work', 'built', 'house'), ('work', 'built', 'house', 'straw')],
 [('second', 'little', 'pig', 'worked'),
  ('little', 'pig', 'worked', 'little'),
  ('pig', 'worked', 'little', 'bit'),
  ('worked', 'little', 'bit', 'harder'),
  ('little', 'bit', 'harder', 'somewhat'),
  ('bit', 'harder', 'somewhat', 'lazy'),
  ('harder', 'somewhat', 'lazy', 'built'),
  ('somewhat', 'lazy', 'built', 'house'),
  ('lazy', 'built', 'house', 'sticks')],
 [('then,', 'sang', 'danced', 'played'),
  ('sang', 'danced', 'played', 'together'),
  ('danced', 'played', 'together', 'rest'),
  ('played', 'together', 'rest', 'day')],
 [('the', 'third', 'little', 'pig'),
  ('third', 'little', 'pig', 'worked'),
  ('little', 'pig', 'worked', 'hard'),
  ('pig', 'worked', 'hard', 'day'),
  ('worked', 'hard', 'day', 'built'),
  ('hard', 'day', 'built', 'house'),
  ('day', 'built', 'house', 'bricks')],
 [('sturdy', 'house', 'complete', 'fine'),
  ('house', 'complete', 'fine', 'fireplace'),
  ('complete', 'fine', 'fireplace', 'chimney')],
 [('looked', 'like', 'could', 'withstand'),
  ('like', 'could', 'withstand', 'strongest'),
  ('could', 'withstand', 'strongest', 'winds')],
 []]

In [141]:
# TF_IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_vect = TfidfVectorizer()
data2_tf_idf = []
tf_idf_vect.fit(data2)
data2_tf_idf.append(tf_idf_vect.transform(data2).toarray())
data2_tf_idf

[array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.26462499, 0.31129006,
         0.        , 0.        , 0.        , 0.31129006, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.20583395, 0.        , 0.31129006, 0.26462499, 0.20583395,
         0.31129006, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.31129006, 0.        ,
         0.        , 0.31129006, 0.31129006, 0.        , 0.31129006,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.36429589, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.42853734,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.36429589, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.42853734, 0.42853734, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.42853734],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.54884133, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.46656527, 0.        ,
         0.3629097 , 0.        , 0.        , 0.        , 0.3629097 ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.46656527, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.37231379, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.33101364, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.50060377,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.50060377, 0.        , 0.        , 0.50060377, 0.        ,
         0.        ],
        [0.32238303, 0.        , 0.23976576, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.32238303, 0.21316894, 0.27405502, 0.        ,
         0.42633789, 0.        , 0.        , 0.        , 0.21316894,
         0.        , 0.        , 0.        , 0.        , 0.32238303,
         0.        , 0.        , 0.32238303, 0.32238303, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.27405502,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.38568218, 0.32786509, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.38568218, 0.38568218, 0.38568218, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.38568218,
         0.        , 0.        , 0.        , 0.38568218, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.37708286, 0.28044764, 0.        , 0.        ,
         0.        , 0.        , 0.32055488, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.37708286, 0.        , 0.24933805, 0.        , 0.        ,
         0.24933805, 0.        , 0.        , 0.        , 0.24933805,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.32055488, 0.        , 0.        ,
         0.37708286, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.32055488,
         0.        ],
        [0.        , 0.        , 0.        , 0.42885592, 0.42885592,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.42885592, 0.42885592, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.28357189, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.42885592, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.40824829, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.40824829,
         0.        , 0.40824829, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.40824829, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.40824829, 0.40824829, 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]])]

# EXERCICE 3

In [24]:
import pandas as pd
data3 = pd.read_csv("train_rel_2.tsv",delimiter="\t")

In [25]:
data3

,Id,EssaySet,Score1,Score2,EssayText
0,1,1,1,1,Some additional information that we would need...
1,2,1,1,1,"After reading the expirement, I realized that ..."
2,3,1,1,1,"What you need is more trials, a control set up..."
3,4,1,0,0,The student should list what rock is better an...
4,5,1,2,2,For the students to be able to make a replicat...
...,...,...,...,...,...
17038,27584,10,1,1,white :: white becuase if you live in a hot pl...
17039,27585,10,1,1,light gray :: This color will affect the dogho...
17040,27586,10,1,1,light gray :: i think light gray would work th...
17041,27587,10,1,0,dark gray :: if they painted the doghouse dar...
17042,27588,10,0,1,white :: the black would affect the doghouse b...

In [26]:
# Convertir en lower
for i in range(len(data3)):
    data3["EssayText"][i] = data3["EssayText"][i].lower()
data3

C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2432594610.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3["EssayText"][i] = data3["EssayText"][i].lower()

,Id,EssaySet,Score1,Score2,EssayText
0,1,1,1,1,some additional information that we would need...
1,2,1,1,1,"after reading the expirement, i realized that ..."
2,3,1,1,1,"what you need is more trials, a control set up..."
3,4,1,0,0,the student should list what rock is better an...
4,5,1,2,2,for the students to be able to make a replicat...
...,...,...,...,...,...
17038,27584,10,1,1,white :: white becuase if you live in a hot pl...
17039,27585,10,1,1,light gray :: this color will affect the dogho...
17040,27586,10,1,1,light gray :: i think light gray would work th...
17041,27587,10,1,0,dark gray :: if they painted the doghouse dar...
17042,27588,10,0,1,white :: the black would affect the doghouse b...

In [27]:
# Supprimer les ponctuations et lemmatization
import string
import nltk
from nltk.stem import WordNetLemmatizer
ponc = string.punctuation
wnl = WordNetLemmatizer()
for i in range(len(data3)):
    data3["EssayText"][i] = nltk.word_tokenize(data3["EssayText"][i])
    data3["EssayText"][i] = [w for w in data3["EssayText"][i] if w not in ponc]
    data3["EssayText"][i] = [wnl.lemmatize(w) for w in data3["EssayText"][i]]
    data3["EssayText"][i] = " ".join(data3["EssayText"][i])
data3

C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/1203863987.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3["EssayText"][i] = nltk.word_tokenize(data3["EssayText"][i])
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/1203863987.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3["EssayText"][i] = [w for w in data3["EssayText"][i] if w not in ponc]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/1203863987.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3["EssayText"][i] = [wnl.lemmatize(w) for w in data3["EssayText"][i]]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/1203863987.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3["EssayText"][i] = " ".join(data3["EssayText"][i])

,Id,EssaySet,Score1,Score2,EssayText
0,1,1,1,1,some additional information that we would need...
1,2,1,1,1,after reading the expirement i realized that t...
2,3,1,1,1,what you need is more trial a control set up a...
3,4,1,0,0,the student should list what rock is better an...
4,5,1,2,2,for the student to be able to make a replicate...
...,...,...,...,...,...
17038,27584,10,1,1,white white becuase if you live in a hot place...
17039,27585,10,1,1,light gray this color will affect the doghouse...
17040,27586,10,1,1,light gray i think light gray would work the b...
17041,27587,10,1,0,dark gray if they painted the doghouse dark gr...
17042,27588,10,0,1,white the black would affect the doghouse beca...

In [30]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_vect = TfidfVectorizer()
data3_tf_idf = []
tf_idf_vect.fit(data3["EssayText"])
data3_tf_idf.append(tf_idf_vect.transform(data3["EssayText"]).toarray())
data3_tf_idf

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])]

# Exercice 4

In [41]:
!pip install pyspark

Requirement already satisfied: pyspark in c:\users\adnane\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: py4j==0.10.9.5 in c:\users\adnane\anaconda3\lib\site-packages (from pyspark) (0.10.9.5)

In [45]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
sc = SparkContext.getOrCreate()
spark = SparkSession(sc)
data4 = spark.read.json("News_Category_Dataset.json")

DataFrame[authors: string, category: string, date: string, headline: string, link: string, short_description: string]

In [55]:
data4.show()

+--------------------+-------------+----------+--------------------+--------------------+--------------------+
|             authors|     category|      date|            headline|                link|   short_description|
+--------------------+-------------+----------+--------------------+--------------------+--------------------+
|     Melissa Jeltsen|        CRIME|2018-05-26|There Were 2 Mass...|https://www.huffi...|She left her husb...|
|       Andy McDonald|ENTERTAINMENT|2018-05-26|Will Smith Joins ...|https://www.huffi...|Of course it has ...|
|          Ron Dicker|ENTERTAINMENT|2018-05-26|Hugh Grant Marrie...|https://www.huffi...|The actor and his...|
|          Ron Dicker|ENTERTAINMENT|2018-05-26|Jim Carrey Blasts...|https://www.huffi...|The actor gives D...|
|          Ron Dicker|ENTERTAINMENT|2018-05-26|Julianna Margulie...|https://www.huffi...|The "Dietland" ac...|
|          Ron Dicker|ENTERTAINMENT|2018-05-26|Morgan Freeman 'D...|https://www.huffi...|"It is not right ...|
|          Ron Dicker|ENTERTAINMENT|2018-05-26|Donald Trump Is L...|https://www.huffi...|It's catchy, all ...|
|     Todd Van Luling|ENTERTAINMENT|2018-05-26|What To Watch On ...|https://www.huffi...|There's a great m...|
|       Andy McDonald|ENTERTAINMENT|2018-05-26|Mike Myers Reveal...|https://www.huffi...|Myer's kids may b...|
|     Todd Van Luling|ENTERTAINMENT|2018-05-26|What To Watch On ...|https://www.huffi...|You're getting a ...|
|   Sebastian Murdock|ENTERTAINMENT|2018-05-26|Justin Timberlake...|https://www.huffi...|The pop star also...|
|                    |   WORLD NEWS|2018-05-26|South Korean Pres...|https://www.huffi...|The two met to pa...|
|       Karen Pinchin|       IMPACT|2018-05-26|With Its Way Of L...|https://www.huffi...|The revolution is...|
|Elise Foley and R...|     POLITICS|2018-05-26|Trump's Crackdown...|https://www.huffi...|Last month a Heal...|
|Michael Isikoff, ...|     POLITICS|2018-05-26|'Trump's Son Shou...|https://www.huffi...|The wiretaps feat...|
|      Mary Papenfuss|     POLITICS|2018-05-26|Edward Snowden: T...|https://www.huffi...|But don't count o...|
|      Mary Papenfuss|     POLITICS|2018-05-26|Booyah: Obama Pho...|https://www.huffi...|Just a peeping mi...|
|       Laura Bassett|     POLITICS|2018-05-26|Ireland Votes To ...|https://www.huffi...|Irish women will ...|
|      Chris D'Angelo|     POLITICS|2018-05-26|Ryan Zinke Looks ...|https://www.huffi...|The interior secr...|
|      Mary Papenfuss|     POLITICS|2018-05-26|Trump's Scottish ...|https://www.huffi...|And there are fou...|
+--------------------+-------------+----------+--------------------+--------------------+--------------------+
only showing top 20 rows

In [98]:
data44 = pd.read_json('News_Category_Dataset.json', lines=True)

In [99]:
data44

,short_description,headline,date,link,authors,category
0,She left her husband. He killed their children...,There Were 2 Mass Shootings In Texas Last Week...,2018-05-26,https://www.huffingtonpost.com/entry/texas-ama...,Melissa Jeltsen,CRIME
1,Of course it has a song.,Will Smith Joins Diplo And Nicky Jam For The 2...,2018-05-26,https://www.huffingtonpost.com/entry/will-smit...,Andy McDonald,ENTERTAINMENT
2,The actor and his longtime girlfriend Anna Ebe...,Hugh Grant Marries For The First Time At Age 57,2018-05-26,https://www.huffingtonpost.com/entry/hugh-gran...,Ron Dicker,ENTERTAINMENT
3,The actor gives Dems an ass-kicking for not fi...,Jim Carrey Blasts 'Castrato' Adam Schiff And D...,2018-05-26,https://www.huffingtonpost.com/entry/jim-carre...,Ron Dicker,ENTERTAINMENT
4,"The ""Dietland"" actress said using the bags is ...",Julianna Margulies Uses Donald Trump Poop Bags...,2018-05-26,https://www.huffingtonpost.com/entry/julianna-...,Ron Dicker,ENTERTAINMENT
...,...,...,...,...,...,...
124984,,Why I Thought I'd Never Live To See 33,2014-04-18,https://www.huffingtonpost.com/entry/a-black-g...,,WOMEN
124985,I often hear people describe cooking for one a...,Five Tips For Cooking For One,2014-04-18,https://www.huffingtonpost.com/entry/five-tips...,"Food Riot, ContributorPlay with your food.",TASTE
124986,,Police Want your Home Video Surveillance Footage,2014-04-18,https://www.huffingtonpost.com/entry/police-wa...,"Robert Siciliano, ContributorPersonal Security...",CRIME
124987,,"Ouch, Natalie Morales",2014-04-18,https://www.huffingtonpost.com/entry/natalie-m...,Katherine Fung,MEDIA
124988,"Our thoughts and feelings are powerful, but ma...",Reasons Not to Be Happy,2014-04-18,https://www.huffingtonpost.com/entry/happiness...,"Mindy Utay, Contributor""Calming Life's Conflicts""",HEALTHY LIVING

In [100]:
# Supprimer les ponctuations, convertir en lower, supprimer les stop words & stemming
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
stm = PorterStemmer()
stpw = set(stopwords.words('english'))
ponc = string.punctuation
for i in range(1000):
    data44["headline"][i] = data44["headline"][i].lower()
    data44["short_description"][i] = data44["short_description"][i].lower()
    data44["headline"][i] = nltk.word_tokenize(data44["headline"][i])
    data44["short_description"][i] = nltk.word_tokenize(data44["short_description"][i])
    data44["headline"][i] = [w for w in data44["headline"][i] if w not in ponc]
    data44["short_description"][i] = [w for w in data44["short_description"][i] if w not in ponc]
    data44["headline"][i] = [w for w in data44["headline"][i] if w not in stpw]
    data44["short_description"][i] = [w for w in data44["short_description"][i] if w not in stpw]
    data44["headline"][i] = [stm.stem(w) for w in data44["headline"][i]]
    data44["short_description"][i] = [stm.stem(w) for w in data44["short_description"][i]]
    data44["headline"][i] = " ".join(data44["headline"][i])
    data44["short_description"][i] = " ".join(data44["short_description"][i])
data44

C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["headline"][i] = data44["headline"][i].lower()
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["short_description"][i] = data44["short_description"][i].lower()
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["headline"][i] = nltk.word_tokenize(data44["headline"][i])
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["short_description"][i] = nltk.word_tokenize(data44["short_description"][i])
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["headline"][i] = [w for w in data44["headline"][i] if w not in ponc]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["short_description"][i] = [w for w in data44["short_description"][i] if w not in ponc]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["headline"][i] = [w for w in data44["headline"][i] if w not in stpw]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["short_description"][i] = [w for w in data44["short_description"][i] if w not in stpw]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["headline"][i] = [stm.stem(w) for w in data44["headline"][i]]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["short_description"][i] = [stm.stem(w) for w in data44["short_description"][i]]
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["headline"][i] = " ".join(data44["headline"][i])
C:\Users\adnane\AppData\Local\Temp/ipykernel_5896/2211546541.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data44["short_description"][i] = " ".join(data44["short_description"][i])

,short_description,headline,date,link,authors,category
0,left husband kill children anoth day america,2 mass shoot texa last week 1 tv,2018-05-26,https://www.huffingtonpost.com/entry/texas-ama...,Melissa Jeltsen,CRIME
1,cours song,smith join diplo nicki jam 2018 world cup 's o...,2018-05-26,https://www.huffingtonpost.com/entry/will-smit...,Andy McDonald,ENTERTAINMENT
2,actor longtim girlfriend anna eberstein tie kn...,hugh grant marri first time age 57,2018-05-26,https://www.huffingtonpost.com/entry/hugh-gran...,Ron Dicker,ENTERTAINMENT
3,actor give dem ass-kick fight hard enough dona...,jim carrey blast 'castrato adam schiff democra...,2018-05-26,https://www.huffingtonpost.com/entry/jim-carre...,Ron Dicker,ENTERTAINMENT
4,`` dietland '' actress said use bag `` realli ...,julianna marguli use donald trump poop bag pic...,2018-05-26,https://www.huffingtonpost.com/entry/julianna-...,Ron Dicker,ENTERTAINMENT
...,...,...,...,...,...,...
124984,,Why I Thought I'd Never Live To See 33,2014-04-18,https://www.huffingtonpost.com/entry/a-black-g...,,WOMEN
124985,I often hear people describe cooking for one a...,Five Tips For Cooking For One,2014-04-18,https://www.huffingtonpost.com/entry/five-tips...,"Food Riot, ContributorPlay with your food.",TASTE
124986,,Police Want your Home Video Surveillance Footage,2014-04-18,https://www.huffingtonpost.com/entry/police-wa...,"Robert Siciliano, ContributorPersonal Security...",CRIME
124987,,"Ouch, Natalie Morales",2014-04-18,https://www.huffingtonpost.com/entry/natalie-m...,Katherine Fung,MEDIA
124988,"Our thoughts and feelings are powerful, but ma...",Reasons Not to Be Happy,2014-04-18,https://www.huffingtonpost.com/entry/happiness...,"Mindy Utay, Contributor""Calming Life's Conflicts""",HEALTHY LIVING

In [101]:
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
short_description = []
headline = []
for i in range(1000):
    short_description.append(data44["short_description"][i])
    headline.append(data44["headline"][i])
vectorizer.fit(short_description)
vectorizer.fit(headline)
short_description_bag_of_words = vectorizer.transform(short_description)
headline_bag_of_words = vectorizer.transform(headline)

In [102]:
short_description_bag_of_words

<1000x3061 sparse matrix of type '<class 'numpy.int64'>'
	with 6203 stored elements in Compressed Sparse Row format>

In [103]:
headline_bag_of_words

<1000x3061 sparse matrix of type '<class 'numpy.int64'>'
	with 8272 stored elements in Compressed Sparse Row format>

# TF_IDF

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_vect = TfidfVectorizer()
short_description_tf_idf = []
headline_tf_idf = []
tf_idf_vect.fit(headline)
tf_idf_vect.fit(short_description)
headline_tf_idf.append(tf_idf_vect.transform(headline).toarray())
short_description_tf_idf.append(tf_idf_vect.transform(short_description).toarray())
short_description_tf_idf

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])]

# 4-grams

In [105]:
import re
from nltk.util import ngrams
def n_gramme(data, n):
    data_n_gramme = list(ngrams(data,n))
    return data_n_gramme

In [106]:
data44_headline_4_gramme = []
data44_short_description_4_gramme = []
for i in range(1000):
    data44_short_description_4_gramme.append(n_gramme(short_description,4))
    data44_headline_4_gramme.append(n_gramme(headline,4))

In [113]:
len(data44_short_description_4_gramme)

1000

In [112]:
len(data44_headline_4_gramme)

1000